### ISSUE TITLE
Cannot find package echo

### ISSUE THREAD

**Issue by hanoisteve** [salrashid123/gcegrpc#4]
coffee:grpc_backend Steven$ go run src/grpc_server.go --grpcport 0.0.0.0:50051
src/grpc_server.go:10:2: cannot find package "echo" in any of:
	/usr/local/Cellar/go/1.12.6/libexec/src/echo (from $GOROOT)
	/Users/Steven/go/src/echo (from $GOPATH)

**Comment by salrashid123** [comment]
i didn't include the compiled proto in as the instructions called out how to do that.

anyway, it makes it easer to get started so i added it in now:  https://github.com/salrashid123/gcegrpc/commit/04df2708b6e02294757f90ffe1899654d6dd3279
