### ISSUE TITLE
Example for Helm installed on GKE

### ISSUE THREAD

**Issue by bweston92** [salrashid123/gcegrpc#6]
Sorry for the lack of relevance to the demo, just struggling to find help.

I have been trying for a few days to get `client_grpc_app (via gRPC wire protocol) --> ingress --> (grpc Service on GKE)`.

I am using Kubernetes `v1.14.8-gke.2`.

My Gateway and VirtualService is up however every time I do a `grpc_cli` it fails. If I visit in the browser I get a 503 and the logs are pretty empty.

Any help would be appreciated.

**Comment by salrashid123** [comment]
As you mentioned `Gateway` and `VirtualService`, are you using Istio here?  If so, the ingress gateway described in this article isn't the same thing as what istio provides.  If you are using the latter,  you can do all that throug istio directly (it creates a network load balancer and GCP doens't know anything about the type of traffic that goes through it (http, grpc).

https://cloud.google.com/solutions/using-istio-for-internal-load-balancing-of-grpc-services
https://github.com/GoogleCloudPlatform/istio-samples
and nonistio, non-gcp ingress but with envoy direct as L4 LB https://cloud.google.com/solutions/exposing-grpc-services-on-gke-using-envoy-proxy

**Comment by bweston92** [comment]
Sorry, yes I am using Istio.

I have the load balancer on GCP that forwards to the ingressgateway. However I am still unable to get this to work with gRPC.
