### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by sn0kerbuzz** [salrashid123/gcegrpc#8]
Hello,

I followed the [istio tutorial](https://github.com/salrashid123/gcegrpc/tree/master/istio), all went well for the setup step, but when verifying external client connectivity this error occurs: `could not greet: rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure`. I'm new to this, so I would appreciate if someone can help me.

Thanks.

**Comment by salrashid123** [comment]
i just updated the instructions for istio `1.7.2`..

https://github.com/salrashid123/gcegrpc/tree/master/istio

ther'es a race condition with the certs and ingress gateway which i didn't figure out yet so i just 'reload' the gateway after deployment 

```bash
INGRESS_POD_NAME=$(kubectl get po -n istio-system | grep ingressgateway\- | awk '{print$1}'); echo ${INGRESS_POD_NAME};
kubectl delete po/$INGRESS_POD_NAME -n istio-system
```

**Comment by sn0kerbuzz** [comment]
Thanks, works perfectly.
